### ISSUE TITLE
[Bug]: RuntimeError: Unexpected error from cudaGetDeviceCount()

### ISSUE THREAD

**Issue by chenxinlong** [lllyasviel/Fooocus#2626]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [ ] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [X] The issue has been reported before but has not been fixed yet

### What happened?

I've build the image from Dockerfile and try to run it in kubernetes. But it show errors as follow : 
```
root@fooocus-app-6589d5b68c-6z9d6:/content# ./entrypoint.sh --listen
ln: failed to create symbolic link '/content/app/outputs': File exists
[System ARGV] ['launch.py', '--listen']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.3.0
Environment: config_path = /content/data/config.txt
Environment: config_example_path = /content/data/config_modification_tutorial.txt
Environment: path_checkpoints = /content/data/models/checkpoints/
Environment: path_loras = /content/data/models/loras/
Environment: path_embeddings = /content/data/models/embeddings/
Environment: path_vae_approx = /content/data/models/vae_approx/
Environment: path_upscale_models = /content/data/models/upscale_models/
Environment: path_inpaint = /content/data/models/inpaint/
Environment: path_controlnet = /content/data/models/controlnet/
Environment: path_clip_vision = /content/data/models/clip_vision/
Environment: path_fooocus_expansion = /content/data/models/prompt_expansion/fooocus_expansion/
Environment: path_outputs = /content/app/outputs/
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Traceback (most recent call last):
  File "/content/app/launch.py", line 136, in <module>
    from webui import *
  File "/content/app/webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "/content/app/modules/async_worker.py", line 3, in <module>
    from modules.patch import PatchSettings, patch_settings, patch_all
  File "/content/app/modules/patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "/content/app/ldm_patched/modules/model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/content/app/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/content/app/ldm_patched/ldm/modules/attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/content/app/ldm_patched/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "/content/app/ldm_patched/modules/model_management.py", line 121, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/content/app/ldm_patched/modules/model_management.py", line 90, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
root@fooocus-app-6589d5b68c-6z9d6:/content#
root@fooocus-app-6589d5b68c-6z9d6:/content#
root@fooocus-app-6589d5b68c-6z9d6:/content# nvidia-smi
Mon Mar 25 15:15:51 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.98                 Driver Version: 535.98       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080        Off | 00000000:03:00.0 Off |                  N/A |
| 44%   56C    P0              81W / 320W |      1MiB / 10240MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

### Steps to reproduce the problem

1. make images
```
FROM nvidia/cuda:12.3.1-base-ubuntu22.04
ENV DEBIAN_FRONTEND noninteractive
ENV CMDARGS --listen

RUN apt-get update -y && \
	apt-get install -y curl libgl1 libglib2.0-0 python3-pip python-is-python3 git && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*

RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple

COPY requirements_docker.txt requirements_versions.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements_docker.txt -r /tmp/requirements_versions.txt && \
	rm -f /tmp/requirements_docker.txt /tmp/requirements_versions.txt
RUN pip install --no-cache-dir xformers==0.0.23 --no-dependencies

# RUN curl -fsL -o /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2 https://cdn-media.huggingface.co/frpc-gradio-0.2/frpc_linux_amd64 && \
# 	chmod +x /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2
RUN ls /usr/local/lib/python3.10/dist-packages/gradio/
COPY frpc_linux_amd64 /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2 
RUN	chmod +x /usr/local/lib/python3.10/dist-packages/gradio/frpc_linux_amd64_v0.2

RUN adduser --disabled-password --gecos '' user && \
	mkdir -p /content/app /content/data

COPY entrypoint.sh /content/
RUN chown -R user:user /content

WORKDIR /content
USER root

RUN git clone https://github.com/lllyasviel/Fooocus /content/app
RUN mv /content/app/models /content/app/models.org

CMD [ "sh", "-c", "/content/entrypoint.sh ${CMDARGS}" ]
```
2. run it as a  kubernetes deployment : 
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fooocus-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fooocus-app
  template:
    metadata:
      labels:
        app: fooocus-app
    spec:
      nodeName: "worker002"
      runtimeClassName: nvidia
      containers:
      - name: fooocus-app
        image: images.xxx.com/proj1/fooocus:2.3.0
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 7865
        volumeMounts:
        - name: fooocus-data
          mountPath: /content/data
        - name: fooocus-output
          mountPath: /content/app/outputs
        resources:
          requests:
            gpu.xxx.com/GA102_GEFORCE_RTX_3080: 1
            cpu: 2
            memory: 12Gi
          limits:
            gpu.xxx.com/GA102_GEFORCE_RTX_3080: 1
            cpu: 2
            memory: 12Gi
        command:
          - sleep
          - infinity
        env:
        - name: CMDARGS
          value: "--listen"
        - name: DATADIR
          value: /content/data
        - name: config_path
          value: /content/data/config.txt
        - name: config_example_path
          value: /content/data/config_modification_tutorial.txt
        - name: path_checkpoints
          value: /content/data/models/checkpoints/
        - name: path_loras
          value: /content/data/models/loras/
        - name: path_embeddings
          value: /content/data/models/embeddings/
        - name: path_vae_approx
          value: /content/data/models/vae_approx/
        - name: path_upscale_models
          value: /content/data/models/upscale_models/
        - name: path_inpaint
          value: /content/data/models/inpaint/
        - name: path_controlnet
          value: /content/data/models/controlnet/
        - name: path_clip_vision
          value: /content/data/models/clip_vision/
        - name: path_fooocus_expansion
          value: /content/data/models/prompt_expansion/fooocus_expansion/
        - name: path_outputs
          value: /content/app/outputs/
      volumes:
      - name: fooocus-data
        hostPath:
          path: /root/cxl/fooocus/data/
          type: Directory
      - name: fooocus-output
        hostPath:
          path: /root/cxl/fooocus/outputs/
          type: Directory
      terminationGracePeriodSeconds: 30
```
3. run it 
```
kubectl apply -f deployment.yaml
```

4. login into pod, run fooocus

```
kubectl exec -it <pod> -- ./entrypoint.sh --listen
```

### What should have happened?

I've tried https://github.com/lllyasviel/Fooocus/issues/2169 reboot the nvidia driver or event reboot the machine. But it doesn't work.

### What browsers do you use to access Fooocus?

Google Chrome

### Where are you running Fooocus?

Cloud (other)

### What operating system are you using?

Ubuntu22.04

### Console logs

```Shell
ln: failed to create symbolic link '/content/app/outputs': File exists
[System ARGV] ['launch.py', '--listen']
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Fooocus version: 2.3.0
Environment: config_path = /content/data/config.txt
Environment: config_example_path = /content/data/config_modification_tutorial.txt
Environment: path_checkpoints = /content/data/models/checkpoints/
Environment: path_loras = /content/data/models/loras/
Environment: path_embeddings = /content/data/models/embeddings/
Environment: path_vae_approx = /content/data/models/vae_approx/
Environment: path_upscale_models = /content/data/models/upscale_models/
Environment: path_inpaint = /content/data/models/inpaint/
Environment: path_controlnet = /content/data/models/controlnet/
Environment: path_clip_vision = /content/data/models/clip_vision/
Environment: path_fooocus_expansion = /content/data/models/prompt_expansion/fooocus_expansion/
Environment: path_outputs = /content/app/outputs/
[Cleanup] Attempting to delete content of temp dir /tmp/fooocus
[Cleanup] Cleanup successful
Traceback (most recent call last):
  File "/content/app/launch.py", line 136, in <module>
    from webui import *
  File "/content/app/webui.py", line 10, in <module>
    import modules.async_worker as worker
  File "/content/app/modules/async_worker.py", line 3, in <module>
    from modules.patch import PatchSettings, patch_settings, patch_all
  File "/content/app/modules/patch.py", line 5, in <module>
    import ldm_patched.modules.model_base
  File "/content/app/ldm_patched/modules/model_base.py", line 2, in <module>
    from ldm_patched.ldm.modules.diffusionmodules.openaimodel import UNetModel, Timestep
  File "/content/app/ldm_patched/ldm/modules/diffusionmodules/openaimodel.py", line 15, in <module>
    from ..attention import SpatialTransformer, SpatialVideoTransformer, default
  File "/content/app/ldm_patched/ldm/modules/attention.py", line 9, in <module>
    from .sub_quadratic_attention import efficient_dot_product_attention
  File "/content/app/ldm_patched/ldm/modules/sub_quadratic_attention.py", line 27, in <module>
    from ldm_patched.modules import model_management
  File "/content/app/ldm_patched/modules/model_management.py", line 121, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/content/app/ldm_patched/modules/model_management.py", line 90, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
```

### Additional information

host os nvidia versions: 
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.98                 Driver Version: 535.98       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080        Off | 00000000:03:00.0 Off |                  N/A |
|  0%   57C    P0              81W / 320W |      1MiB / 10240MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

container nvidia version:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.98                 Driver Version: 535.98       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3080        Off | 00000000:03:00.0 Off |                  N/A |
|  0%   57C    P0              84W / 320W |      1MiB / 10240MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```
