### ISSUE TITLE
API NOT generate  image

### ISSUE THREAD

**Issue by energy888666** [lllyasviel/Fooocus#449]
如何利用api添加prompt生成图片,  我
代码如下,最终没有生成图片
`
from gradio_client import Client

client = Client("http://127.0.0.1:7860", serialize=False)

my_prompts=[
  {
    "positive": "modern sports car",
    "negative": "rusty"
  },
  {
    "positive": "retro sports car",
    "negative": "broken"
  }
]

universal_negative = "blurry, drawn, painted, unrealistic"

for index, prompt in enumerate(my_prompts):
  seed = 1337
  negative=prompt["negative"]
  image = client.predict(
    prompt["positive"],                                                 # parameter_8: str (prompt)
    f"{universal_negative}, {negative}",                  # negative_prompt: str
    ["Fooocus V2"],                                                     # image_style: List[str] (style_selections)
    "Speed",                                                            # performance: str (performance_selction)
    "1024×1024",                                                        # aspect_ratios: str (aspect_ratios_selction)
    1,                                                                  # image_number: int (image_number)
    seed,                                                               # seed: int (image_seed)
    2,                                                                  # sampling_sharpness: int (sharpness)
    "sd_xl_base_1.0_0.9vae.safetensors",                                # sdxl_base_model: str (base_model_name)
    "sd_xl_refiner_1.0_0.9vae.safetensors",                             # sdxl_refiner: str (refiner_model_name)
    "sd_xl_offset_example-lora_1.0.safetensors",                        # sdxl_lora_1: str (l1)
    0.5,                                                                # weight: float (w1)
    "None",                                                             # sdxl_lora_2: str (l2)
    0.5,                                                                # weight: float (w2)
    "None",                                                             # sdxl_lora_3: str (l3)
    0.5,                                                                # weight: float (w3)
    "None",                                                             # sdxl_lora_4: str (l4)
    0.5,                                                                # weight: float (w4)
    "None",                                                             # sdxl_lora_5: str (l5)
    0.5,                                                                # weight: float (w5)
    False,                                                              # input_image: bool (input_image_checkbox)
    # "disabled",                                                         # method: str (uov_method)
    # "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mJ0GgAA", # drag_above_image_to_here: str (base64 image)
    fn_index=7                                                         # fn_index: int (api endpoint)
  )
  print(image)`
 结果 如下:
Loaded as API: http://127.0.0.1:7860/ ✔
({'visible': True, '__type__': 'update', 'mode': 'dynamic'}, {'visible': False, '__type__': 'update'}, [])
({'visible': True, '__type__': 'update', 'mode': 'dynamic'}, {'visible': False, '__type__': 'update'}, [])

**Comment by TimothyAlexisVass** [comment]
Duplicate of #246

**Comment by energy888666** [comment]
> Duplicate of #246
Thanks!

**Comment by PhanThanhTrung** [comment]
I'm sorry. I have the same issue here.
First of all, I tried:
```
from gradio_client import Client
client = Client("http://127.0.0.1:7860/", serialize=False)
print(client._render_endpoints_info)
```
The output is:
```
- predict(parameter_8, negative_prompt, image_style, performance, aspect_ratios, image_number, seed, sampling_sharpness, sdxl_base_model, sdxl_refiner, sdxl_lora_1, weight, sdxl_lora_2, weight, sdxl_lora_3, weight, sdxl_lora_4, weight, sdxl_lora_5, weight, input_image, parameter_30, upscale_or_variation, drag_above_image_to_here, outpaint, drag_above_image_to_here, fn_index=13) -> (value_4, preview, gallery)
    Parameters:
     - [Textbox] parameter_8: str 
     - [Textbox] negative_prompt: str 
     - [Checkboxgroup] image_style: List[str] 
     - [Radio] performance: str 
     - [Radio] aspect_ratios: str 
     - [Slider] image_number: int | float (numeric value between 1 and 32) 
     - [Number] seed: int | float 
     - [Slider] sampling_sharpness: int | float (numeric value between 0.0 and 30.0) 
     - [Dropdown] sdxl_base_model: str (Option from: ['sd_xl_refiner_1.0_0.9vae.safetensors', 'sd_xl_base_1.0_0.9vae.safetensors']) 
     - [Dropdown] sdxl_refiner: str (Option from: ['None', 'sd_xl_refiner_1.0_0.9vae.safetensors', 'sd_xl_base_1.0_0.9vae.safetensors']) 
     - [Dropdown] sdxl_lora_1: str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) 
     - [Slider] weight: int | float (numeric value between -2 and 2) 
     - [Dropdown] sdxl_lora_2: str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) 
     - [Slider] weight: int | float (numeric value between -2 and 2) 
     - [Dropdown] sdxl_lora_3: str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) 
     - [Slider] weight: int | float (numeric value between -2 and 2) 
     - [Dropdown] sdxl_lora_4: str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) 
     - [Slider] weight: int | float (numeric value between -2 and 2) 
     - [Dropdown] sdxl_lora_5: str (Option from: ['None', 'sd_xl_offset_example-lora_1.0.safetensors']) 
     - [Slider] weight: int | float (numeric value between -2 and 2) 
     - [Checkbox] input_image: bool 
     - [Textbox] parameter_30: str 
     - [Radio] upscale_or_variation: str 
     - [Image] drag_above_image_to_here: str (base64 representation of an image) 
     - [Checkboxgroup] outpaint: List[str] 
     - [Image] drag_above_image_to_here: str (base64 representation of an image) 
    Returns:
     - [Html] value_4: str 
     - [Image] preview: str (base64 representation of an image) 
     - [Gallery] gallery: Tuple[Dict(name: str (name of file), data: str (base64 representation of file), size: int (size of image in bytes), is_file: bool (true if the file has been uploaded to the server), orig_name: str (original name of the file)), str | None] 

 - predict(fn_index=14) -> (value_10, value_11)
    Parameters:
     - None
    Returns:
     - [Button] value_10: str 
     - [Button] value_11: str 
>
```
I want to use `fn_index=13` to get the base64 representation of the image to the client. My code looks like this:
```
from gradio_client import Client

client = Client("http://127.0.0.1:7860/", serialize=False)
result = client.predict(
				"Howdy!",	# str in 'parameter_8' Textbox component
				"Howdy!",	# str in 'Negative Prompt' Textbox component
				["Fooocus V2"],	# List[str] in 'Image Style' Checkboxgroup component
				"Speed",	# str in 'Performance' Radio component
				"704×1408",	# str in 'Aspect Ratios' Radio component
				1,	# int | float (numeric value between 1 and 32) in 'Image Number' Slider component
				5,	# int | float in 'Seed' Number component
				0,	# int | float (numeric value between 0.0 and 30.0) in 'Sampling Sharpness' Slider component
				"sd_xl_base_1.0_0.9vae.safetensors",	# str (Option from: []) in 'SDXL Base Model' Dropdown component
				"sd_xl_refiner_1.0_0.9vae.safetensors",	# str (Option from: ['None']) in 'SDXL Refiner' Dropdown component
				"sd_xl_offset_example-lora_1.0.safetensors",	# str (Option from: ['None']) in 'SDXL LoRA 1' Dropdown component
				0.5,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
				"None",	# str (Option from: ['None']) in 'SDXL LoRA 2' Dropdown component
				0.5,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
				"None",	# str (Option from: ['None']) in 'SDXL LoRA 3' Dropdown component
				0.5,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
				"None",	# str (Option from: ['None']) in 'SDXL LoRA 4' Dropdown component
				0.5,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
				"None",	# str (Option from: ['None']) in 'SDXL LoRA 5' Dropdown component
				0.5,	# int | float (numeric value between -2 and 2) in 'Weight' Slider component
				False,	# bool in 'Input Image' Checkbox component
				"Howdy!",	# str in 'parameter_30' Textbox component
				"Disabled",	# str in 'Upscale or Variation:' Radio component
				None,	# str (filepath or URL to image) in 'Drag above image to here' Image component
				[],	# List[str] in 'Outpaint' Checkboxgroup component
				None,	# str (filepath or URL to image) in 'Drag above image to here' Image component
				fn_index=13
)
```
And instead of giving me the base64 of the image, the output of `result` is:
```
({'visible': False, '__type__': 'update'}, {'visible': False, '__type__': 'update'}, {'visible': True, 'value': [{'name': '/tmp/gradio/e3c17dc839b4490480eb6727ca850cc4cfbdfa03/image.png', 'data': None, 'is_file': True}], '__type__': 'update'})
```
What can I do to get the base64 representation of the predicted image?
