### ISSUE TITLE
Run in docker

### ISSUE THREAD

**Issue by DrMartiner** [lllyasviel/Fooocus#98]

**Comment by dstrop** [comment]
i will just leave this here
```
FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

RUN apt-get update && \
    apt-get install --no-install-recommends -y python3 python3-pip && \
    rm -rf /var/lib/apt/lists/*

RUN --mount=type=cache,target=/root/.cache/pip pip3 install virtualenv
RUN mkdir /app

WORKDIR /app

RUN virtualenv /venv
RUN . /venv/bin/activate && \
    pip3 install --upgrade pip

COPY requirements_versions.txt /app/requirements_versions.txt
RUN . /venv/bin/activate && \
    pip3 install -r requirements_versions.txt

COPY . /app/

ENTRYPOINT [ "bash", "-c", ". /venv/bin/activate && exec \"$@\"", "--" ]
CMD [ "python3", "launch.py", "--listen" ]
```

```
version: "3.3"
services:
  testui:
    container_name: testui
    build:
      context: .
    ports:
      - "7860:7860"
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
```
